### ISSUE TITLE
Install over USB don't work

### ISSUE THREAD

**Issue by Niemandausduisburg** [mrdude2478/Tinwoo-Release#1]
My Switch is not recognized when connected to USB. No drive is shown.

When you could fix it it would a good alternative to FBI

**Comment by badablek** [comment]
this is not an issue. You missed one thing : install over USB is NOT the same as MTP mode (from DBI)

as stated on GBAtemp :
_Installs NSP/NSZ/XCI/XCZ files over LAN or **USB from tools such as** [NS-USBloader](https://github.com/developersu/ns-usbloader)_

so, basically :
- when using MTP mode (DBI), yes, your switch appears as multiples drives and you can copy/paste files (computer side)
- when using **Install over USB**, you MUST use some tool (ns-usbloader) to setup a basic file server (computer side), then you will be able to see and choose what you want (switch side)

ps : you will also need libusbk driver from zadig ! Don't forget it or it will not work.


BTW, MTP mode would be nice on Tinwoo Installer 👍
