### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by catfromplan9** [mrdude2478/Tinwoo-Release#4]
Awoo Installer is licensed under the GNU GPLv3. You seem to think that you can just link to Awoo's repository and no longer be in violation of the GPLv3. Yea, no, that's not how it works. Here's a summary of the license

https://www.tldrlegal.com/license/gnu-general-public-license-v3-gpl-3

> Any modifications to or software including (via compiler) GPL-licensed code must also be made available under the GPL along with build & install instructions.

Tinleaf uses code from Awoo, and so it is also available under the GPLv3.

You need to either:
A. Rewrite Tinwoo to remove all code from Tinleaf and Awoo
B. Provide Tinwoo's source code under the GPLv3

If you fail to take action, I will be contacting GitHub and having this repository taken down for violations of the GPLv3. License violations are illegal. If you reupload this elsewhere, I will contact the hosting providers and have it taken down. Consider complying and save yourself the hassle.

**Comment by mrdude2478** [comment]
Contact who you want.

**Comment by catfromplan9** [comment]
Eat shit cocksucker
